#!/usr/bin/env python3
"""
Rebuild TOPIC_MAP.md from existing classified files.
"""

import yaml
from pathlib import Path

def main():
    project_root = Path("E:/Boom Project")
    indexes_dir = project_root / "Knowledge" / "indexes"
    indexes_dir.mkdir(parents=True, exist_ok=True)
    
    # Topic keywords from config
    topic_keywords = {
        "astrology": ["astrology", "natal", "transit", "synastry", "horary", "vedic", "western", "uranian", "nakshatra", "dasa", "bhava", "graha", "rashi", "planet", "house", "sign", "aspect", "conjunction", "opposition", "trine", "square", "sextile"],
        "psychology": ["psychology", "psychological", "attachment", "trauma", "belief", "cognitive", "behavior", "personality", "shadow", "jung", "freud", "archetype", "projection", "defense", "mechanism"],
        "relationships": ["relationship", "soulmate", "marriage", "partnership", "compatibility", "love", "dating", "romantic", "intimacy", "commitment", "divorce", "breakup"],
        "financial-astrology": ["financial", "market", "trading", "gold", "bitcoin", "stock", "index", "volatility", "timing", "entry", "exit"],
        "methodology": ["methodology", "framework", "model", "system", "approach", "technique", "process", "pipeline", "workflow"],
        "critique": ["critique", "criticism", "review", "audit", "evaluation", "assessment", "flaw", "gap", "weakness", "strength"],
        "convergence": ["convergence", "synthesis", "integration", "cross-domain", "multi-perspective", "unified", "combined"],
        "technical": ["technical", "extraction", "calculation", "computation", "algorithm", "formula", "precision", "accuracy"],
    }
    
    topic_map = {}
    output_dir = project_root / "Output"
    
    for agent_folder in output_dir.iterdir():
        if not agent_folder.is_dir():
            continue
        
        for md_file in agent_folder.glob("*.md"):
            content = md_file.read_text(encoding="utf-8")
            
            if not content.startswith("---"):
                continue
            
            parts = content.split("---", 2)
            if len(parts) < 3:
                continue
            
            try:
                fm = yaml.safe_load(parts[1]) or {}
            except:
                continue
            
            tags = fm.get("tags", [])
            rel_path = str(md_file.relative_to(project_root))
            
            for tag in tags:
                if tag in topic_keywords or tag.startswith("date:"):
                    if tag not in topic_map:
                        topic_map[tag] = []
                    if rel_path not in topic_map[tag]:
                        topic_map[tag].append(rel_path)
    
    # Write TOPIC_MAP.md
    lines = ["# TOPIC_MAP.md", "", "Auto-generated by Libby.", ""]
    for topic, files in sorted(topic_map.items()):
        lines.append(f"## {topic}")
        for f in sorted(files):
            lines.append(f"- {f}")
        lines.append("")
    
    topic_map_path = indexes_dir / "TOPIC_MAP.md"
    topic_map_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  [OK] TOPIC_MAP.md ({len(topic_map)} topics)")

if __name__ == "__main__":
    main()