#!/usr/bin/env python
"""
hermes.core.spec — generate the architecture spec and skill registry docs.

The old system maintained `AGENTS.md` (a hand-written 139-skill inventory) and
`HERMES_ORCHESTRATOR.md` (routing + architecture in one 29 KB file). Both went
stale the moment a skill changed. This module GENERATES them from the registry,
so documentation cannot drift from reality.
"""
from __future__ import annotations

import io
import os
from collections import defaultdict

from .registry import Registry
from .skill import SkillManager, LIVE_ROOT

BOOM = os.environ.get("BOOM_ROOT", r"E:\Boom Project")
SPEC_PATH = os.path.join(BOOM, "core", "SPEC.md")
REGISTRY_DOC = os.path.join(BOOM, "core", "SKILL_REGISTRY.md")


def build_spec(reg: Registry) -> str:
    sm = SkillManager(reg)
    cost = sm.prompt_cost()
    st = reg.stats()
    live = lambda k: st.get(k, 0) - st.get(f"{k}_deprecated", 0)  # noqa: E731
    return f"""# Hermes Core — Architecture Spec (v2, post-rebuild)

Generated by `python -m core.spec`. Do not edit by hand.

## Scope

Hermes itself (`hermes-agent`) is an upstream Nous Research git-installed product
(`v0.21.5+7331.g6590f13`). It is **configured, never forked** — rebuilding its
internals is neither possible nor intended. This spec governs the BooM user
layer: `core/`, the live skill root, `config/`, and the memory stores.

## Components

| Module | Responsibility | Invariant |
|---|---|---|
| `core/registry.py` | discovery | only index of what exists; descriptors never exceed 400 chars |
| `core/router.py` | orchestration | returns ONE primary + capped secondaries; never a body |
| `core/policy.py` | decision support | JEV default is NEVER escalate; triggers must fire |
| `core/context.py` | token control | load() refuses bodies over budget; release() returns tokens |
| `core/skill.py` | methodology | one live root; oversized bodies flagged for split |
| `core/script.py` | execution | registry-discovered; AST scan, never import |
| `core/agent.py` | specialist workers | delegation only when context absorbed > overhead |
| `core/memory.py` | memory | Notes = truth, index = retrieval, runtime = context |
| `core/project.py` | context boundary | rejects out-of-boundary paths |
| `core/validator.py` | validation | named criteria with evidence, no optimism |
| `core/tests.py` | regression | routing accuracy is a tracked number |
| `core/spec.py` | documentation | generates this file and SKILL_REGISTRY.md |

## Token architecture

```
SEARCH -> RETRIEVE -> LOAD -> EXECUTE -> COMPRESS -> RELEASE
```

Preloading is prohibited and mechanically prevented:
- skill descriptions are the only per-turn injection ({cost['description_chars']} chars
  across {cost['skills']} skills, ~{cost['description_tokens']} tokens)
- skill bodies total ~{cost['body_tokens']} tokens and load one at a time
- `ContextManager.load()` refuses anything over `max_single` and records a
  `load_denied` trace when it does
- discovery returns descriptors only

## Memory architecture

```
Notes (markdown)  -> SOURCE OF TRUTH
index (sqlite)    -> RETRIEVAL / SEARCH   (disposable, rebuildable)
holographic       -> RUNTIME CONTEXT      (char-budgeted)
```

Hermes is never a database of record. The index is disposable: `prune_missing()`
removes rows whose file is gone, `reindex_all_notes()` rebuilds from Notes.
`.rebuild/` and `.quarantine/` are excluded from retrieval — they mirror or
retire the project and must never be cited as live knowledge.

## Skill system

Skill = methodology. Script = execution. Exactly one load-bearing skill root:
`{LIVE_ROOT}`. Nested `<category>/<name>/SKILL.md` layout is supported; a name
present at both levels is a duplicate and is refused at publish time.

Aliases in `core/skill.py:ROUTE_ALIASES` are the routing vocabulary. Phrase
aliases match on substring or on all significant words, so "rebuild the output
index" hits the alias "rebuild index".

## Agent system

Hermes -> Agent Manager -> Specialist Agent -> Skill -> Tool/Script.
Workers return only Finding / Files / Symbol-Section / Evidence / Confidence.
`validate_finding()` rejects raw payloads (cap 4000 chars, no raw keys), so
context isolation is enforced rather than requested.

Agent responsibilities are checked by `AgentManager.overlaps()` against domain
vocabulary with a generic-noun stop list, so "research"/"extraction" do not
produce false duplicates.

## MCP layer

- `ask-jev` — Decision Support. Gated by `core/policy.py`. Denylisted for
  astrology interpretation, routine navigation, transit calculation, file
  reads, index queries.
- `docker` gateway — tool integration.

Notes MCP, retrieval MCP and Files MCP are **not yet built**. The rebuild
specified them; they remain open work (see OPERATING.md).

## Current inventory

| Kind | Live | Deprecated |
|---|---|---|
| skills | {live('skill')} | {st.get('skill_deprecated', 0)} |
| scripts | {live('script')} | {st.get('script_deprecated', 0)} |
| agents | {live('agent')} | {st.get('agent_deprecated', 0)} |
| mcp | {live('mcp')} | {st.get('mcp_deprecated', 0)} |
| projects | {live('project')} | {st.get('project_deprecated', 0)} |

## Validation

`python -m core.validator` runs 12 criteria. `python -m core.tests` measures
routing accuracy. Both must be green before any change is reported as done.
"""


def build_registry_doc(reg: Registry) -> str:
    sm = SkillManager(reg)
    by_cat: dict[str, list] = defaultdict(list)
    for info in sm.scan():
        key = info.category or "(top level)"
        flag = ""
        if info.oversized:
            flag = f" [OVERSIZED {info.size}c]"
        if any(p.startswith("DUPLICATE") for p in info.problems):
            flag = " [DUPLICATE]"
        if not info.description:
            flag = " [NO DESCRIPTION]"
        by_cat[key].append((info, flag))

    out = io.StringIO()
    out.write("# Skill Registry (generated)\n\n")
    out.write("Generated by `python -m core.spec`. Do not edit by hand.\n\n")
    c = sm.prompt_cost()
    out.write(f"- live root: `{LIVE_ROOT}`\n")
    out.write(f"- total skills: **{c['skills']}**\n")
    out.write(f"- preloaded per turn: ~{c['description_tokens']} tokens "
              f"({c['description_chars']} chars)\n")
    out.write(f"- lazy bodies: ~{c['body_tokens']} tokens\n")
    out.write(f"- oversized (>12000 chars): {c['oversized']}\n\n")
    for cat in sorted(by_cat):
        out.write(f"## {cat}\n\n")
        for info, flag in sorted(by_cat[cat], key=lambda x: x[0].name):
            desc = (info.description or "(none)")[:110]
            out.write(f"- **{info.name}**{flag} — {desc}\n")
        out.write("\n")
    return out.getvalue()


def main() -> int:
    reg = Registry()
    open(SPEC_PATH, "w", encoding="utf-8").write(build_spec(reg))
    open(REGISTRY_DOC, "w", encoding="utf-8").write(build_registry_doc(reg))
    print(f"wrote {SPEC_PATH}")
    print(f"wrote {REGISTRY_DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())