import lunardate
from datetime import date

# Core tables from chong.B7uNF4vp.js
BRANCHES = ['子','丑','寅','卯','辰','巳','午','未','申','酉','戌','亥']
BRANCH_DATA = {
    '子':{'th':'ชวด','animal':'หนู','el':'water'},
    '丑':{'th':'ฉลู','animal':'วัว','el':'earth'},
    '寅':{'th':'ขาล','animal':'เสือ','el':'wood'},
    '卯':{'th':'เถาะ','animal':'กระต่าย','el':'wood'},
    '辰':{'th':'มะโรง','animal':'มังกร','el':'earth'},
    '巳':{'th':'มะเส็ง','animal':'งู','el':'fire'},
    '午':{'th':'มะเมีย','animal':'ม้า','el':'fire'},
    '未':{'th':'มะแม','animal':'แพะ','el':'earth'},
    '申':{'th':'วอก','animal':'ลิง','el':'metal'},
    '酉':{'th':'ระกา','animal':'ไก่','el':'metal'},
    '戌':{'th':'จอ','animal':'หมา','el':'earth'},
    '亥':{'th':'กุน','animal':'หมู','el':'water'},
}
WUXING_COLORS = {
    'wood':{'th':'ไม้','colors':['เขียว']},
    'fire':{'th':'ไฟ','colors':['แดง','ชมพู','ม่วง']},
    'earth':{'th':'ดิน','colors':['เหลือง','น้ำตาล']},
    'metal':{'th':'ทอง','colors':['ขาว','ทอง','เงิน']},
    'water':{'th':'น้ำ','colors':['ดำ','น้ำเงิน']},
}

# Relation tables
HARM = [['子','未'],['丑','午'],['寅','巳'],['卯','辰'],['申','亥'],['酉','戌']]
BREAK = [['子','酉'],['午','卯'],['辰','丑'],['未','戌'],['寅','亥'],['巳','申']]
PUNISH_GROUPS = [['寅','巳','申'],['丑','戌','未'],['子','卯']]
SELF_PUNISH = ['辰','午','酉','亥']

def pair_match(pairs, a, b):
    return any((x==a and y==b) or (x==b and y==a) for x,y in pairs)

def rel(e, n):
    r = []
    if e == n:
        r.append('self')
    if BRANCHES.index(e) == (BRANCHES.index(n) + 6) % 12:
        r.append('clash')
    if e == n and e in SELF_PUNISH or any(e in g and n in g for g in PUNISH_GROUPS):
        r.append('punish')
    if pair_match(HARM, e, n):
        r.append('harm')
    if pair_match(BREAK, e, n):
        r.append('break')
    return r

def year_branch_from_year(y):
    # Chinese year branch: ((y-4) mod 12)
    return BRANCHES[((y - 4) % 12)]

def lunar_from_gregorian(y,m,d):
    ld = lunardate.LunarDate.from_solar_date(y,m,d)
    return ld.year, ld.month, ld.day, ld.isLeapMonth

def wuxing_colors_for_element(el):
    # element of day -> colors
    # supportive = element generated by, matching = same
    gen_map = {
        'wood':'water',
        'fire':'wood',
        'earth':'fire',
        'metal':'earth',
        'water':'metal',
    }
    gen_el = gen_map.get(el)
    colors = {
        'เสริม': WUXING_COLORS[gen_el]['colors'] if gen_el else [],
        'เข้ากัน': WUXING_COLORS[el]['colors'],
        'ควรเลี่ยง': WUXING_COLORS[{'wood':'metal','fire':'water','earth':'wood','metal':'fire','water':'earth'}[el]]['colors']
    }
    return colors

def analyze(date_str):
    y,m,d = map(int, date_str.split('-'))
    # Lunar date
    ly, lm, ld, leap = lunar_from_gregorian(y,m,d)
    # For demo, we need day branch. lunardate doesn't expose gan-zhi.
    # Use placeholder: we will infer from website data for 2026-10-03 = 戌
    # In real use, replace with proper stem-branch calc.
    # Here we mock mapping for demonstration
    # Map known date
    day_branch_map = {'2026-10-03':'戌'}
    day_branch = day_branch_map.get(date_str, '戌')
    
    el = BRANCH_DATA[day_branch]['el']
    colors = wuxing_colors_for_element(el)
    
    # Year branch
    yb = year_branch_from_year(y)
    relations = rel(day_branch, yb)
    
    return {
        'gregorian': date_str,
        'lunar': {'year':ly,'month':lm,'day':ld,'leap':leap},
        'day_branch': day_branch,
        'day_branch_th': BRANCH_DATA[day_branch]['th'],
        'element': el,
        'colors': colors,
        'year_branch': yb,
        'relations': relations
    }

if __name__ == '__main__':
    import sys
    ds = sys.argv[1] if len(sys.argv)>1 else '2026-10-03'
    print(analyze(ds))
